import React from "react";
import Head from "next/head";
import Citrouille from "../components/Citrouille";
import Dune from "../components/halloween/dune";
import Main from "../styles/page/halloween/main";

const Halloween = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Dune/>
      </Main>
    </div>
  );
};

export default Halloween;
