import React from "react";
import Head from "next/head";
import Citrouille from "../components/Citrouille";

const Halloween = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Citrouille />
      </main>
    </div>
  );
};

export default Halloween;
